--- # Ansible Role [PHP]: tasks.ubuntu.copy_php_cli_config (Axel Pardemann <axelitus@GitHub>)
- name: Check if PHP {{ axelitus_php_ver }} CLI extension is installed
  command: dpkg-query -l php{{ axelitus_php_ver }}-cli
  register: php_cli_exists
  failed_when: php_cli_exists.rc > 1
  changed_when: no

- name: Copy PHP {{ axelitus_php_ver }} CLI ini file if CLI installed
  template:
    src: "{{ axelitus_php_cli_ini_template }}"
    dest: "{{ axelitus_php_cli_ini_path }}"
    owner: "root"
    group: "root"
  when: php_cli_exists|succeeded
  register: php_copy_cli_ini