--- # Ansible Role [PHP]: tasks.ubuntu.install_php_extensions (Axel Pardemann <axelitus@GitHub>)
- name: Install PHP extensions
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ php.extensions }}"
  when: php_install|succeeded
  register: php_install_extensions

- name: Enable Xdebug remote debugging
  lineinfile:
    dest: "/etc/php/{{ php.ver }}/mods-available/xdebug.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^xdebug.remote_enable', line: "xdebug.remote_enable=on" }
    - { regexp: '^xdebug.remote_connect_back', line: "xdebug.remote_connect_back=on" }
  when: php_install_extensions|succeeded