--- # Ansible Role [PHP]: tasks.ubuntu.install_php_extensions (Axel Pardemann <axelitus@GitHub>)
- name: Install PHP {{ php.ver }} extensions
  apt:
    name: "php{{ php.ver }}-{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ php.extensions }}"
  when: php_install|succeeded
  register: php_install_extensions