--- # Ansible Role [PHP]: tasks.ubuntu.copy_php_fpm_config (Axel Pardemann <axelitus@GitHub>)
- name: Check if PHP {{ php.ver }} FPM extension is installed
  command: dpkg-query -l php{{ php.ver }}-fpm
  register: php_fpm_installed
  failed_when: php_fpm_installed.rc > 1
  changed_when: no

- name: Ensure PHP {{ php.ver }} slow log directory
  file:
    path: "{{ phplog.path }}"
    owner: "{{ phplog.owner }}"
    group: "{{ phplog.group }}"
    state: directory
    mode: 0755

- name: Copy PHP {{ php.ver }} FPM conf file if FPM installed
  template:
    src: "{{ phpfpm.conf.template }}"
    dest: "{{ phpfpm.conf.path }}"
    owner: "{{ phpfpm.conf.owner }}"
    group: "{{ phpfpm.conf.group }}"
  when: php_fpm_installed|succeeded
  register: php_fpm_conf_copied

- name: Copy PHP {{ php.ver }} FPM ini file if FPM installed
  template:
    src: "{{ phpfpm.ini.template }}"
    dest: "{{ phpfpm.ini.path }}"
    owner: "{{ phpfpm.ini.owner }}"
    group: "{{ phpfpm.ini.group }}"
  when: php_fpm_installed|succeeded
  register: php_fpm_ini_copied

- name: Copy PHP {{ php.ver }} FPM pool conf files if FPM installed
  template:
    src: "fpm/pools/{{ item.key }}.conf.j2"
    dest: "{{ phpfpm.pool.path }}/{{ item.key }}.conf"
    owner: "{{ item.value.owner }}"
    group: "{{ item.value.group }}"
  with_dict: "{{ phpfpm.pool.files }}"
  when: php_fpm_installed|succeeded
  register: php_fpm_pools_copied
  notify:
    - Restart PHP-FPM service